#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
<<<<<<< HEAD
name: TikilluaritSMS

# Short bio or description (displayed in the header)
description: Inissaqarnermut/inuuniarnermut apeqqutit?

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: ./images/small-Greenland.png
=======
name: Antlers and Anchors || Michael-Owen Liston

# Short bio or description (displayed in the header)
description: Design portfolio and blog of Michael-Owen Liston

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://127.0.0.1:4000/images/little_headshot_50x50.jpeg
>>>>>>> first_build

#
# Flags below are optional
#

# I’m implementing the (currently beta) collections feature
# here for the portfolio pages

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Adding phone number and email variables
# so I don’t forget to change it
current_phone_number: +1-647-574-3325
current_email_address: michaelowen.liston [at] gmail.com

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: michael@antlersandanchors.ca
  facebook: 
  flickr: 
<<<<<<< HEAD
  github:
=======
  github: antlersanchors
>>>>>>> first_build
  instagram: 
  linkedin: michaelowenliston
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
<<<<<<< HEAD
  twitter:
=======
  twitter: AntlersAnchors
>>>>>>> first_build
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
<<<<<<< HEAD
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://tikilluarit.dk
=======
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: http://antlersandanchors.ca
url: http://127.0.0.1:4000
>>>>>>> first_build

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
<<<<<<< HEAD
baseurl: "/tikilluarit_site"
=======
baseurl:
>>>>>>> first_build

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
